common:
  msg_source: 1                                         #0: not use Lidar
                                                        #1: packet message comes from online Lidar
                                                        #2: packet message comes from ROS or ROS2
                                                        #3: packet message comes from Pcap file
                                                        #4: packet message comes from Protobuf-UDP
                                                        #5: point cloud comes from Protobuf-UDP
  send_packet_ros: false                                #true: Send packets through ROS or ROS2(Used to record packet)
  send_point_cloud_ros: true                            #true: Send point cloud through ROS or ROS2
  send_packet_proto: false                              #true: Send packets through Protobuf-UDP
  send_point_cloud_proto: false                         #true: Send point cloud through Protobuf-UDP
  pcap_path: /home/robosense/lidar.pcap                 #The path of pcap file

lidar:
  - driver:
      lidar_type: RS80            #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: rslidar_80           #Frame id of message
      msop_port: 29955           #Msop port of lidar 192.168.1.203
      difop_port: 17733             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp  
      x: 0
      y: 0
      z: 0
      roll: 0
      pitch: 0
      yaw: 0
    ros:
      ros_recv_packet_topic: /rslidar_packets_80          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rslidar_packets_80          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /rslidar_points_80      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60021                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60021                     #Port number which the point cloud will be send to
      msop_recv_port: 60022                            #Port number used for receiving lidar msop packets
      msop_send_port: 60022                            #Port number which the msop packets will be send to 
      difop_recv_port: 60023                           #Port number used for receiving lidar difop packets
      difop_send_port: 60023                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 192.168.3.112                   #Ip address which the point cloud will be send to 
      packet_send_ip: 192.168.3.112                        #Ip address which the lidar packets will be send to
  - driver:
      lidar_type: RSHELIOS            #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: rslidar_16_right         #Frame id of message
      msop_port: 16699           #Msop port of lidar
      difop_port: 17788             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp
      x: 0
      y: 0
      z: 0
      roll: 0
      pitch: 0
      yaw: 0  
    ros:
      ros_recv_packet_topic: /rslidar_packets_16_right          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rslidar_packets_16_right          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /rslidar_points_16_right      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60021                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60021                     #Port number which the point cloud will be send to
      msop_recv_port: 60022                            #Port number used for receiving lidar msop packets
      msop_send_port: 60022                            #Port number which the msop packets will be send to 
      difop_recv_port: 60023                           #Port number used for receiving lidar difop packets
      difop_send_port: 60023                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 192.168.3.112                   #Ip address which the point cloud will be send to 
      packet_send_ip: 192.168.3.112                        #Ip address which the lidar packets will be send to
  - driver:
      lidar_type: RS16            #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: rslidar_16_left          #Frame id of message
      msop_port: 9903           #Msop port of lidar
      difop_port: 6699             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp 
      x: 0
      y: 0
      z: 0
      roll: 0
      pitch: 0
      yaw: 0 
    ros:
      ros_recv_packet_topic: /rslidar_packets_16_left          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rslidar_packets_16_left          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /rslidar_points_16_left      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60021                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60021                     #Port number which the point cloud will be send to
      msop_recv_port: 60022                            #Port number used for receiving lidar msop packets
      msop_send_port: 60022                            #Port number which the msop packets will be send to 
      difop_recv_port: 60023                           #Port number used for receiving lidar difop packets
      difop_send_port: 60023                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 192.168.3.112                   #Ip address which the point cloud will be send to 
      packet_send_ip: 192.168.3.112                        #Ip address which the lidar packets will be send to
  - driver:
      lidar_type: RSM1            #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: rslidar_m1_207           #Frame id of message
      msop_port: 29966          #Msop port of lidar
      difop_port: 17744             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp
      x: 0
      y: 1.21
      z: 1.18
      roll: 0
      pitch: 0
      yaw: 1.57  
    ros:
      ros_recv_packet_topic: /rslidar_packets_m1_207          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rslidar_packets_m1_207        #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /rslidar_points_m1_207      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60021                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60021                     #Port number which the point cloud will be send to
      msop_recv_port: 60022                            #Port number used for receiving lidar msop packets
      msop_send_port: 60022                            #Port number which the msop packets will be send to 
      difop_recv_port: 60023                           #Port number used for receiving lidar difop packets
      difop_send_port: 60023                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 192.168.3.112                   #Ip address which the point cloud will be send to 
      packet_send_ip: 192.168.3.112                        #Ip address which the lidar packets will be send to
  - driver:
      lidar_type: RSM1            #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: rslidar_m1           #Frame id of message
      msop_port: 15399          #Msop port of lidar
      difop_port: 19578             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp  
      x: 0
      y: 1.21
      z: 1.18
      roll: 0
      pitch: 0
      yaw: 1.57
    ros:
      ros_recv_packet_topic: /rslidar_packets_m1          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rslidar_packets_m1          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /rslidar_points_m1      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60021                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60021                     #Port number which the point cloud will be send to
      msop_recv_port: 60022                            #Port number used for receiving lidar msop packets
      msop_send_port: 60022                            #Port number which the msop packets will be send to 
      difop_recv_port: 60023                           #Port number used for receiving lidar difop packets
      difop_send_port: 60023                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 192.168.3.112                   #Ip address which the point cloud will be send to 
      packet_send_ip: 192.168.3.112                        #Ip address which the lidar packets will be send to
